name: ttc_dlc
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.7.9
  - numpy=1.19.2
  - pytorch=1.7.0
  - pytorch-lightning=1.0.8
  - pandas=1.1.3
  - albumentations=1.0.3
  - torchvision=0.8.1
  - pillow=9.0.1
  - scikit-learn=1.0.2
  - scikit-image=0.19.2
  - openpyxl=3.0.9
  - pytables=3.7.0
  - tifffile=2022.3.16
  - pip
  - pip:
    - test-tube
    - pytorchcv==0.0.61