name: ttc_seg_fbc
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.7.7
  - numpy=1.21.5
  - pytorch=1.4.0
  - pytorch-lightning=0.7.6
  - pandas=1.1.5
  - albumentations=1.0.3
  - torchvision=0.5.0
  - opencv=4.5.5
  - pillow=9.0.1
  - scikit-learn=1.0.2
  - scikit-image=0.19.2
  - openpyxl=3.0.9
  - pytables=3.7.0
  - xgboost=1.5.1
  - skrebate=0.62
  - mlxtend=0.19.0
  - scipy=1.7.3
  - xlrd=2.0.1
  - joblib=1.1.0
  - seaborn=0.11.2
  - tifffile=2022.3.16
  - pip
  - pip:
    - test-tube
